apiVersion: v1
kind: ConfigMap
metadata:
  name: medingest-config
  namespace: default
data:
  MINIO_ENDPOINT: "minio-service:9000"
  NATS_URL: "nats://nats-service:4222"
  TEMPORAL_URL: "temporal-service:7233"
