apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digifax.fullname" . }}-secrets
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl }}
  REDIS_URL: {{ .Values.secrets.redisUrl }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey }}
