"""
eclinicalworks_exporter.py

Outbound EHR integration adapter for eClinicalWorks (eCW) Electronic Health Record systems.
This module implements the IEhrExporter port interface to enable secure transmission of clinical
patient data packaged as FHIR R4 Bundle payloads to external eClinicalWorks clinical endpoints.
"""

import logging
from typing import Any, cast

import requests

from src.application.ports.iehr_exporter import IEhrExporter

# Set up logging for tracking eClinicalWorks integration metrics and events
logger = logging.getLogger(__name__)


class EClinicalWorksExporter(IEhrExporter):
    """
    Concrete adapter for exporting clinical documents/data to eClinicalWorks (eCW) EHR systems.

    This adapter manages:
      - Authenticating against eClinicalWorks OAuth servers using the Client Credentials Flow.
      - Injecting necessary custom routing headers required by eCW (such as facility/hub IDs).
      - Guaranteeing once-only delivery semantics using unique idempotency checks.
      - Formatting standard FHIR R4 requests and parsing JSON results.
    """

    def __init__(
        self,
        auth_url: str,
        fhir_url: str,
        client_id: str,
        client_secret: str,
        custom_headers: dict[str, str] | None = None
    ):
        """
        Initializes the eClinicalWorks adapter with target configuration parameters.

        Args:
            auth_url (str): The authorization server endpoint URL where OAuth tokens are requested.
            fhir_url (str): The target base FHIR resource path or transactional endpoint on the EHR.
            client_id (str): The programmatic key identifying this MedIngest integration client.
            client_secret (str): The secure credential associated with client_id used for OAuth.
            custom_headers (dict[str, str] | None): Optional dictionary of headers required by eCW,
                such as facility identifiers, tenant routing tags, or enterprise metadata.
        """
        self.auth_url = auth_url
        self.fhir_url = fhir_url
        self.client_id = client_id
        self.client_secret = client_secret
        self.custom_headers = custom_headers or {}
        # In-memory database context mimicking once-only delivery checks.
        # Keeps track of already processed transaction keys to prevent duplicate records in case of retries.
        self._processed_keys: set[str] = set()

    def _get_access_token(self) -> str:
        """
        Requests a temporary OAuth 2.0 access token from the configured authorization URL.

        Uses the standard client_credentials grant type, passing client credentials
        in the request body payload.

        Returns:
            str: Valid bearer access token string.

        Raises:
            requests.exceptions.HTTPError: If the token exchange request fails (e.g., status code != 200).
        """
        logger.info("Requesting access token from eClinicalWorks OAuth authority...")
        
        # Prepare the standard OAuth body payload
        data = {
            "grant_type": "client_credentials",
            "client_id": self.client_id,
            "client_secret": self.client_secret
        }
        
        # Send POST request to token service with a 10s socket timeout
        res = requests.post(self.auth_url, data=data, timeout=10)
        res.raise_for_status()
        
        # Parse and return access token from the JSON response object
        token = str(res.json()["access_token"])
        logger.debug("Successfully acquired access token from eClinicalWorks.")
        return token

    def export_bundle(self, bundle: dict[str, Any], idempotency_key: str) -> dict[str, Any]:
        """
        Transmits a clinical data FHIR R4 Bundle to the remote eClinicalWorks platform.

        This method encapsulates authorization, custom enterprise headers mapping,
        idempotency validation, and raw HTTP POST actions.

        Args:
            bundle (dict[str, Any]): The FHIR R4 Bundle dict payload.
            idempotency_key (str): Unique transaction string generated by the ingestion
                pipeline to ensure the document is not processed multiple times.

        Returns:
            dict[str, Any]: Dict containing success metadata, response document ID,
                or detailed failure statuses.
        """
        # Step 1: Assert idempotency. If this transaction key has already succeeded, bypass
        if idempotency_key in self._processed_keys:
            logger.info(f"Duplicate export attempt detected and bypassed for eClinicalWorks. Key: {idempotency_key}")
            return {"document_id": bundle.get("id"), "status": "duplicate_bypassed"}

        try:
            # Step 2: Acquire token. Raises exception if credentials or server endpoint are invalid
            token = self._get_access_token()
            
            # Step 3: Compose HTTP headers including authentication and standard metadata
            headers = {
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/fhir+json",
                "X-Idempotency-Key": idempotency_key
            }
            # Step 4: Apply facility-specific headers (hub routing identifiers, app IDs)
            headers.update(self.custom_headers)

            logger.info(f"Posting clinical bundle (ID: {bundle.get('id')}) to eClinicalWorks endpoint: {self.fhir_url}")
            
            # Step 5: Post the JSON payload to target clinical endpoint with 15s timeout
            res = requests.post(self.fhir_url, json=bundle, headers=headers, timeout=15)

            # Step 6: Evaluate response. Standard HTTP 200 OK or 201 Created denote success
            if res.status_code in (200, 201):
                # Lock in idempotency context to prevent any downstream duplicate attempts
                self._processed_keys.add(idempotency_key)
                logger.info(f"Clinical bundle successfully synced with eClinicalWorks. Transaction ID: {idempotency_key}")
                return cast(dict[str, Any], res.json())

            # Handle unexpected HTTP errors gracefully, returning status and body content
            logger.warning(f"EHR server returned unexpected status code: {res.status_code}. Response: {res.text}")
            return {"status": "failed", "http_status": res.status_code, "body": res.text}
            
        except Exception as e:
            # Step 7: Log and return localized exception information for system tracing/audits
            logger.error(f"Failed to export bundle to eClinicalWorks: {str(e)}", exc_info=True)
            return {"status": "error", "message": str(e)}
